#!/usr/bin/env sh

command git clone https://github.com/zsh-users/antigen.git $HOME/.cli/antigen

for FILE in .zshrc .npmrc .vimrc
do
  command ln -s $PWD/$FILE $HOME/$FILE
done

command ln -s $PWD/.bin $HOME
