#!/usr/bin/env sh

DOTFILES="$HOME/.dotfiles"

git clone https://github.com/chrstphrknwtn/dotfiles.git $DOTFILES

mkdir -p "$HOME/.cli"
git clone https://github.com/zsh-users/antigen.git "$HOME/.cli/antigen"
git clone https://github.com/chrstphrknwtn/pure.git "$HOME/.cli/pure"

# rc
for FILE in .zshrc .npmrc .vimrc
do
  ln -s $DOTFILES/$FILE $HOME/$FILE
done

# bin
ln -s $DOTFILES/.bin $HOME

# zsh pure
mkdir -p "$HOME/.zfunctions"
ln -s "$HOME/.cli/pure/pure.zsh" "$HOME/.zfunctions/prompt_pure_setup"
ln -s "$HOME/.cli/pure/async.zsh" "$HOME/.zfunctions/async"
