#!/usr/bin/env sh

# C Compile Watch
# Watch a C source file for changes, then compile and run on change.
#
# ccw source.c ./bin

type fswatch >/dev/null 2>&1 || { echo >&2 "ccw: fswatch required: brew install fswatch."; exit 0; }

if [[ $# -ne 2 ]]; then
  echo "\nC Compile Watch\n\n  Usage:  ccw <source.c> <bin>\nExample:  ccw program.c ./program"
else
  command fswatch $1 | (while read; do echo ""; cc -std=c99 $1 -o $2 && $2; done)
fi
