#!/usr/bin/env sh

# C Format
# Format a C source file in a sensible manner.
#
# cfmt source.c

type astyle >/dev/null 2>&1 || { echo >&2 "cfmt: astyle required: brew install astyle."; exit 0; }

if [[ $# -ne 1 ]]; then
  echo "Usage: cfmt <source.c>"
  echo "\nC Format\n\nUsage: cfmt <source.c>"

else
  astyle \
    --style=1tbs \
    --lineend=linux \
    --preserve-date \
    --pad-header \
    --indent=tab \
    --indent-switches \
    --align-pointer=name \
    --align-reference=name \
    --pad-oper \
    --suffix=none \
    $1
fi
