#!/usr/bin/env sh

# Google Cloud Storage
# Create a public website bucket
#
# gcs-mb example.com
# gcs-mb subdomain.example.com eu

if [ "$1" = "" ]; then
  echo 'Specify a bucket domain name'; exit 1;
fi

if [ "$2" ]; then
  REGION=$2;
else
  REGION=us
fi

set -e

command gsutil mb -l $REGION gs://$1
command gsutil acl ch -u allUsers:R gs://$1
command gsutil defacl ch -u allUsers:R gs://$1
command gsutil web set -m index.html -e 404.html gs://$1
