#!/usr/bin/env node
const path = require("path");
const exec = require("child_process").exec;
function exitFailure(message) {
  console.log(message);
  process.exit(1);
}
let pkg;
try {
  pkg = require(path.join(process.cwd(), "package.json"));
} catch (e) {
  if (e.code === "MODULE_NOT_FOUND") {
    exitFailure("Error loading package.json.");
  }
}
if (!pkg.engines || !pkg.engines.node) {
  exitFailure("No node engine specified in package.json.");
}
if (pkg.engines.node.match(/\.x/)) {
  installVersion = pkg.engines.node.substring(0, pkg.engines.node.length - 2);
} else {
  installVersion = pkg.engines.node;
}
console.log(`Switching to node v${installVersion}`);
exec(`n ${installVersion}`, (err, stdout, stderr) => {
  if (err) {
    exitFailure(err);
  }
  console.log(stdout);
});
