#!/usr/bin/env sh

# Swift Compile Watch
# Watch a Swift source file for changes, then compile and run on change with
# time(1)
#
# scw source.swift ./bin

type fswatch >/dev/null 2>&1 || { echo >&2 "scw: fswatch required: brew install fswatch."; exit 0; }

if [[ $# -ne 2 ]]; then
  echo "\nSwift Compile Watch\n\n  Usage:  scw <source.swift> <bin>\nExample:  scw program.swift ./program"
else
  command fswatch $1 | (while read; do echo ""; swiftc -O $1 -o $2 && time $2; done)
fi
