#!/usr/bin/env sh

# Update
#
# Update macOS, homebrew, node, and npm
# and create a manifest of installed packages.

PKG_FILE=$HOME/.dotfiles/.packages

# macOS
# echo "\x1b[38;5;236m[macOS]\x1b[0m"
# softwareupdate --install --all

# brew
echo "\x1b[38;5;236m[brew]\x1b[0m"
brew update && brew upgrade && brew cleanup

# node
echo "\x1b[38;5;236m[node]\x1b[0m"
n lts

# npm
echo "\x1b[38;5;236m[npm]\x1b[0m"
npm update -g

# Create packages manifest
touch $PKG_FILE

# homebrew manifest
echo "[brew]" > $PKG_FILE
brew leaves >> $PKG_FILE

# npm manifest
echo "\n[npm]" >> $PKG_FILE
npm ls -g -p --depth=0 -s | sed -n -e 's/^.*node_modules\///p' >> $PKG_FILE
